import { Bot, ShieldAlert, FileWarning, Sparkles, Loader2 } from "lucide-react"

function DiagnosisCard({ data, loading, onDiagnose, hasFailureData }) {
  if (loading) {
    return (
      <div className="bg-[#131A2A] border border-blue-500/10 rounded-2xl p-6 shadow-xl shadow-blue-500/5">
        <div className="flex flex-col items-center gap-4 py-8">
          <Loader2 className="w-8 h-8 text-blue-400 animate-spin" />
          <div className="text-center">
            <p className="text-blue-400 font-semibold">AI Analyzing...</p>
            <p className="text-gray-500 text-sm mt-1">
              Diagnosing root cause from error logs
            </p>
          </div>
        </div>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="bg-[#131A2A] border border-blue-500/10 rounded-2xl p-6 shadow-xl shadow-blue-500/5">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-blue-500/10 border border-blue-500/20">
            <Bot className="w-5 h-5 text-blue-400" />
          </div>
          <div>
            <h2 className="text-xl font-semibold text-white tracking-wide">
              AI Diagnosis
            </h2>
            <p className="text-sm text-gray-400 mt-1">
              Analyze the failure with AI
            </p>
          </div>
        </div>

        <button
          onClick={onDiagnose}
          disabled={!hasFailureData}
          className={`w-full py-3 rounded-xl font-semibold text-sm transition-all duration-300 cursor-pointer ${
            hasFailureData
              ? "bg-blue-500/20 border border-blue-500/30 text-blue-300 hover:bg-blue-500/30 hover:shadow-lg hover:shadow-blue-500/10"
              : "bg-gray-800/50 border border-gray-700 text-gray-500 cursor-not-allowed"
          }`}
        >
          {hasFailureData
            ? "🔍 Run AI Diagnosis"
            : "Loading failure data..."}
        </button>
      </div>
    )
  }

  return (
    <div className="bg-[#131A2A] border border-blue-500/10 rounded-2xl p-6 shadow-xl shadow-blue-500/5 backdrop-blur-sm">
      {/* HEADER */}
      <div className="flex items-start justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-blue-500/10 border border-blue-500/20">
            <Bot className="w-5 h-5 text-blue-400" />
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white tracking-wide">
              AI Diagnosis
            </h2>
            <p className="text-sm text-gray-400 mt-1">
              Root cause analysis generated by CI Doctor AI
            </p>
          </div>
        </div>

        {/* AI ACTIVE */}
        <div className="flex items-center gap-2 bg-purple-500/10 border border-purple-500/20 px-3 py-1 rounded-full">
          <span className="w-2 h-2 rounded-full bg-purple-400 animate-pulse"></span>
          <span className="text-xs text-purple-300">AI ACTIVE</span>
        </div>
      </div>

      {/* ROOT CAUSE */}
      <div className="bg-black/20 border border-gray-800 rounded-2xl p-5 mb-5">
        <div className="flex items-center gap-2 mb-3">
          <Sparkles className="w-4 h-4 text-blue-400" />
          <h3 className="text-sm font-semibold text-blue-400 uppercase tracking-wide">
            Root Cause
          </h3>
        </div>
        <p className="text-sm text-gray-300 leading-7">{data.rootCause}</p>
      </div>

      {/* CONFIDENCE + RISK */}
      <div className="grid grid-cols-2 gap-4 mb-5">
        {/* CONFIDENCE */}
        <div className="bg-green-500/10 border border-green-500/20 rounded-2xl p-4">
          <p className="text-xs text-green-300 uppercase tracking-wide mb-2">
            Confidence Score
          </p>
          <h3 className="text-3xl font-bold text-green-400">
            {data.confidence}
          </h3>
        </div>

        {/* RISK */}
        <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-2xl p-4">
          <div className="flex items-center gap-2 mb-2">
            <ShieldAlert className="w-4 h-4 text-yellow-400" />
            <p className="text-xs text-yellow-300 uppercase tracking-wide">
              Risk Level
            </p>
          </div>
          <h3 className="text-2xl font-bold text-yellow-400">
            {data.riskLevel}
          </h3>
        </div>
      </div>

      {/* AFFECTED FILES */}
      {data.affectedFiles && data.affectedFiles.length > 0 && (
        <div className="bg-black/20 border border-gray-800 rounded-2xl p-5 mb-5">
          <div className="flex items-center gap-2 mb-4">
            <FileWarning className="w-4 h-4 text-red-400" />
            <h3 className="text-sm font-semibold text-red-400 uppercase tracking-wide">
              Affected Files
            </h3>
          </div>

          <div className="space-y-3">
            {data.affectedFiles.map((file, index) => (
              <div
                key={index}
                className="bg-[#0B1020] border border-gray-800 rounded-xl px-4 py-3 font-mono text-sm text-gray-300"
              >
                {file}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* RECOMMENDATION */}
      <div className="bg-blue-500/10 border border-blue-500/20 rounded-2xl p-5">
        <p className="text-xs text-blue-300 uppercase tracking-wide mb-2">
          Recommended Action
        </p>
        <p className="text-sm text-gray-300 leading-7">
          {data.recommendation}
        </p>
      </div>
    </div>
  )
}

export default DiagnosisCard